export const experienceData = {
	Experience: {
		0: {title: 'Job / Title', designer: 'Designer / Production', role: 'Role / Job', date: 'Date'},
	},
	Film: {
		15: {
			title: 'The Blitz (reshoots)',
			designer: 'Naomi Donne',
			position: 'Makeup Designer',
			role: 'Main team hair and makeup trainee',
			date: 'Nov 2023',
		},
		14: {
			title: 'House of Dragon',
			designer: 'Sara Kramer',
			position: 'Crowd Supervisor',
			role: 'Crowd Makeup artist trainee daily (3 weeks)',
			date: 'Sep 2021',
		},
		13: {
			title: 'The Franchise Pilot',
			designer: 'Naomi Donne',
			position: 'Makeup Designer',
			role: 'Main team hair and makeup trainee',
			date: 'Jun 2023',
		},
		12: {
			title: 'The Friend (Short Film)',
			designer: 'Nanni Mann',
			position: 'Director',
			role: 'Makeup Designer',
			date: 'Apr 2023',
		},
		11: {
			title: 'The Blitz',
			designer: 'Naomi Donne',
			position: 'Makeup Designer',
			role: 'Main team hair and makeup trainee',
			date: 'Mar 2023',
		},
		10: {
			title: 'The  Witcher (Season 3)',
			designer: 'Katherine Warren',
			position: 'Crowd Supervisor',
			role: 'Crowd Makeup artist trainee daily (7 Weeks)',
			date: 'Aug - Sep 2022',
		},
		9: {
			title: 'Bilby',
			designer: 'Naomi Donne',
			position: 'Makeup Designer',
			role: 'Makeup Artist daily',
			date: 'Jul 2022',
		},
		8: {
			title: 'Empire of Light',
			designer: 'Naomi Donne',
			position: 'Makeup Designer',
			role: 'Main team hair and makeup Trainee',
			date: 'Feb - May 2022',
		},
		7: {
			title: 'Allelujah!',
			designer: 'Naomi Donne',
			position: 'Makeup Designer',
			role: 'Main team hair and makeup Trainee',
			date: 'Oct - Dec 2021',
		},
		6: {
			title: 'Tartan',
			designer: 'Madelin Mierzwaik',
			position: 'Crowd Supervisor',
			role: 'Crowd Makeup artist trainee daily',
			date: 'Sep 2021',
		},
		5: {
			title: 'Netflix (6-part docudrama)',
			designer: 'Jo Barass-Short',
			position: 'Makeup Designer, Raw TV',
			role: 'Crowd Makeup artist trainee daily',
			date: 'Apr 2021',
		},
		4: {
			title: 'Perfect 10 (BBC iFeatures film)',
			designer: 'Elizabeth Samways',
			position: 'Production Coordinator',
			designer2: 'Diandra Ferreira',
			position2: 'Makeup Designer',
			role: 'Crowd Makeup artist daily ',
			date: 'Aug 2018',
		},
		3: {
			title: 'The Time Machine (Short film) ',
			designer: 'Matthew Grant',
			position: 'Director',
			role: 'Makeup Artist - SFX',
			date: 'May 2018',
		},
		2: {
			title: 'Roses (Short film)',
			designer: 'Elizabeth Samways',
			position: 'Production Coordinator',
			role: 'Makeup Artist - Beauty & casualty',
			date: 'May 2018',
		},
		1: {
			title: 'Under Glass (Short film)',
			designer: 'James Hart',
			position: 'Director',
			role: 'Crowd Makeup Artist - Men’s makeup',
			date: 'Sep 2017',
		},
	},
	TV_Adverts: {
		8: {
			title: 'Aimate music video',
			designer: 'Emma Robyn',
			position: 'Makeup Designer',
			role: 'Makeup Designer',
			date: 'Nov 2023',
		},
		7: {
			title: 'Genesis Elijah music video',
			designer: 'Cara Laurice Topping',
			position: 'Makeup Designer',
			role: 'Makeup Artist Assistant',
			date: 'Oct 2023',
		},
		6: {
			title: 'ITV’s Goodwood Revival ',
			designer: 'Aurora Media Worldwide',
			role: 'Makeup Artist - Period makeup for Zoe Hardman, for live & recorded segments',
			date: 'Sep 2019',
		},
		5: {
			title: 'Amazon Web Services',
			designer: 'Elizabeth Samways',
			position: 'Production Coordinator, Baerclaw Productions',
			role: 'Makeup Artist',
			date: 'Jun 2019',
		},
		4: {
			title: 'Medical Virtual Reality at Dimension Studios',
			designer: 'Jon Moore',
			position: 'Makeup Designer',
			role: 'Makeup artist assistant - SFX',
			date: 'Jan 2018',
		},
		3: {
			title: 'Horror Video Game at Dimension Studios',
			designer: 'Jon Moore',
			position: 'Makeup Designer',
			role: 'Makeup artist assistant - SFX',
			date: 'Dec 2017',
		},
		2: {
			title: 'Jacob’s Mini Cheddars Advert ',
			designer: 'Carol Hart',
			position: 'Makeup Designer',
			role: 'Makeup Trainee',
			date: 'Apr 2017',
		},
		1: {
			title: 'The Roar App',
			designer: 'The Noise Next Door',
			position: 'Comedy Troupe',
			role: 'Makeup Artist - Men’s Makeup, social media campaign',
			date: 'Oct 2016',
		},
	},
	Theatre: {
		1: {
			title: 'Alcina (local theatre production)',
			designer: 'Joe Paxton',
			position: 'Director',
			role: 'Makeup Artist - Face & body paint',
			date: 'Nov 2016',
		},
	},
	Workshops: {
		1: {
			title: 'ILS ltd SFX Workshop (International Location Safety) ',
			designer: 'ILS ltd',
			role: 'Makeup Artist – SFX casualty makeup tutoring for NGO training program',
			date: 'Oct 2018',
		},
	},
	Fashion: {
		2: {
			title: 'Betty Lou Vintage',
			designer: 'Elizabeth Samways & Emily Dauris',
			position: 'Owners',
			role: 'Makeup Artist - Vintage Themed Weddings & Hen Parties',
			date: 'Jun 2017 - Present',
		},
		1: {
			title: 'Boudoir & Creative Photoshoots',
			designer: 'Susan Grace Hinman - Owner & Photographer',
			role: 'Makeup Artist - Boudoir photoshoots, creative hair & makeup for editorial',
			date: 'May 2017 - May 2021',
		},
	},
	Others: {
		2: {
			title: 'Peaky Blinders Charity Fashion Show',
			designer: 'Stephanie Prior',
			position: 'Host',
			role: 'Makeup Artist',
			date: 'May 2018',
		},
		1: {
			title: 'Brighton University Fashion Show b19/b20',
			designer: 'Brighton University students',
			role: 'Makeup Artist',
			date: 'May 2017',
		},
	},
};

export const expData = [
	{
		id: 1,
		title: 'Netflix 6 part Docu-drama – April 2021',
		designer: 'Jo Barass - Short Makeup Desginer, Raw TV',
		role: 'Crowd Makeup Artist trainee daily',
	},
	{
		id: 2,
		title: 'Perfect 10 (BBC iFeatures film) - Aug 2018',
		designer: 'Elizabeth Samways – Production coordinator',
		role: 'Crowd makeup Artist daily - film featured at BFI festival, London 2019',
	},
	{
		id: 3,
		title: 'The time machine (Short film) - May 2018',
		designer: 'Matthew Grant – Director',
		role: 'Makeup Artist - SFX',
	},
	{
		id: 4,
		title: 'Roses (short student film) - May 2018',
		designer: 'Elizabeth Samways – production coordinator',
		role: 'Makeup Artist - Brighton University film. Beauty & casualty',
	},
	{
		id: 5,
		title: 'Under Glass (short student film) - Sept 2017 shorturl.at/pyGLW',
		designer: 'James Hart - Director',
		role: 'Crowd Makeup Artist - Men’s makeup. Brighton University film',
	},
	{
		id: 6,
		title: 'ITV’s Goodwood Revival – Sept 2019',
		designer: 'Aurora Media Worldwide',
		role: 'Makeup Artist - Period makeup for Zoe Hardman, for live & recorded segments',
	},
	{
		id: 7,
		title: 'Jacob’s mini cheddars Advert – April 2017',
		designer: 'Carol Hart – Makeup Designer',
		role: 'Makeup Trainee',
	},
	{
		id: 8,
		title: 'The Roar App – Oct 2016',
		designer: 'The Noise Next Door Comedy Troupe',
		role: 'Makeup Artist - Men’s Makeup. Social media campaign',
	},
	{
		id: 9,
		title: 'Amazon Web Services - June 2019',
		designer: 'Baerclaw Productions Elizabeth Samways – Production coordinator',
		role: 'Makeup Artist',
	},
	{
		id: 10,
		title: 'Medical Virtual Reality at Dimension Studios – Jan 2018',
		designer: 'Jon Moore – Head makeup designer',
		role: 'Makeup Artist Assistant - VR test shoots for Medical VR. Application & removal of SFX makeup',
	},
	{
		id: 11,
		title: 'Alcina (local theatre production) - Nov 2016',
		designer: 'Joe Paxton - Director',
		role: 'Makeup Artist - face & body paint',
	},
	{
		id: 12,
		title: 'ILS ltd SFX Workshop (International Location Safety) - Oct 2018',
		designer: 'ILS ltd',
		role: 'Makeup Artist – Teaching basic SFX casualty makeup for company’s NGO training program',
	},
	{
		id: 13,
		title: 'Betty Lou Vintage - June 2017 – Present',
		designer: 'Owned by Elizabeth Samways & Emily Dauris',
		role: 'Makeup Artist - Vintage themed Weddings & Hen Parties',
	},
	{
		id: 14,
		title: 'Boudoir & Creative Photoshoots –May2017 – Present (May 2021)',
		designer: 'Susan Grace Hinman - Owner & Photographer',
		role: 'Makeup Artist - Boudoir photoshoot packages offered by creative photographer & creative hair & makeup for editorial',
	},
	{
		id: 15,
		title: 'Self employed – July 2016 - Present',
		designer: 'Self Employed',
		role: 'Makeup Artist - Working on clients for various events, weddings, etc',
	},
	{
		id: 16,
		title: 'Peaky Blinders Charity Fashion show at the Grand Hotel, Brighton – May 2018',
		designer: 'Hosted by Stephanie Prior',
		role: 'Makeup Artist',
	},
	{
		id: 17,
		title: 'Brighton university fashion show b19/b20 - May 2017',
		designer: 'Brighton University students',
		role: 'Makeup Artist',
	},
	{
		id: 18,
		title: 'Horror virtual reality at Dimension Studios – Dec 2017',
		designer: 'Jon Moore – Head makeup designer',
		role: 'Makeup Artist Assistant - Assisting with SFX makeup application & removal',
	},
];
